### PR TITLE
fix: updated .toml and lock file dependencies

### LINKED ISSUE #306: Outdated dependencies (packages not following semantic versioning)
#### Checklist
- [X] I am on the [latest](https://github.com/robinhood-unofficial/pyrh/releases/latest) pyrh version.
- [X] I have searched the [issues](https://github.com/robinhood-unofficial/pyrh/issues) of this repo and believe that this is not a duplicate.

# Description
Pyrh fails to be added to other projects when combined with packages that use updated versions of `certifi` and `pytz`.

# Steps/Code to Reproduce
```
poetry add polygon
poetry add pyrh
```

# Results
```
Because no versions of pyrh match >2.1.1,<3.0.0
 and pyrh (2.1.1) depends on pytz (>=2019.3,<2020.0), pyrh (>=2.1.1,<3.0.0) requires pytz (>=2019.3,<2020.0).
And because pandas (1.5.3) depends on pytz (>=2020.1)
 and no versions of pandas match >1.5.3,<2.0.0, pyrh (>=2.1.1,<3.0.0) is incompatible with pandas (>=1.5.3,<2.0.0).
So, because option-bot depends on both pandas (^1.5.3) and pyrh (^2.1.1), version solving failed.
```

# Versions

```
Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python 3.11.1 (main, Dec 23 2022, 13:33:30) [GCC 11.3.0]
pyrh 2.1.1

### PR DESCRIPTION
**Pull request by jhirschibar**
#### Checklist
- [X] Added **tests** for changed code.
- [X] Updated **documentation** for changed code.
- [X] I've added a news fragment of my changes with the name,
  "{ISSUE_NUM}.{feature|bugfix|doc|removal|misc}""

# Related Issue

Fixes #306, updates certifi and pytz to more recent versions. 
# Description

Versions of certifi and pytz within pyrh were outdated by a few years. These packages follow date structure versioning instead of semantic versioning. Packages using updated versions (eg: 2022's version instead of 2020's version) signals incompatibility within Poetry's dependency resolver when combined with pyrh, so I updated them within pyrh's pyproject.toml and re-wrote the lock file.

### CODE REVIEW

**Comment by adithyabsk** [comment]
seems like a ci error--I'll fix it when I have some time, otherwise feel free to take a stab at it

**Comment by jhirschibar** [comment]
> seems like a ci error--I'll fix it when I have some time, otherwise feel free to take a stab at it

Pre-commit Action was failing to build isort environment. Throwing the error below, so I updated isort to 5.12 in pyproject.toml and the pre-commit-config and it worked locally. 

```
[INFO] Installing environment for https://github.com/pycqa/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/runner/.cache/pre-commit/repog4yvbyy7/py_env-python3/bin/python', '-mpip', 'install', '.', 'toml')
return code: 1
...
RuntimeError: The Poetry configuration is invalid:
            - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'```

**Comment by adithyabsk** [comment]
Merged, thanks for the contribution--until I cut a release, feel free to install from mainline

**Comment by jhirschibar** [comment]
@adithyabsk I'm happy to cut the release and save you the time, but not sure I have credentials for that

**Comment by adithyabsk** [comment]
@jhirschibar no worries, I cut a new release, we had a couple of other minor tweaks that needed to get in either way: https://github.com/robinhood-unofficial/pyrh/releases/tag/v2.1.2

**Pull request merged**
