### PR TITLE
Added optional qr_code argument to SessionManager

### PR DESCRIPTION
**Pull request by scottgl9**

### CODE REVIEW

**Comment by adithyabsk** [comment]
@scottgl9 Thanks for creating a pull request. A few quick questions here. The reason I didn't include the qr code was that it seems that you would not be able to log into Robinhood anywhere else since the mfa source would essentially become this app. That's why using Google Authenticator would be the preferred way of logging in.

**Comment by adithyabsk** [comment]
Nevertheless, the class now allows you to only need to input that password once and the class will auto-refresh the oauth tokens as long as it is running.

**Comment by adithyabsk** [comment]
Additionally, I'm not sure if this would work once the oauth token expires. (ie after 1 day)

**Comment by scottgl9** [comment]
Alright I understand. By the way, are you planning to add crypto trading support to your robinhood python library?

**Comment by adithyabsk** [comment]
@scottgl9 That could certainly be on the roadmap. I wanted to fix the login issues first. I think my next goal is to clean up to trade stocks, then options. If you could create a feature request, we can track progress there.

**Comment by adithyabsk** [comment]
I'm closing this PR but if something changes feel free to re-open.

**Pull request closed without merging**
